### ISSUE TITLE
mentions of Black Magic Sphere

### ISSUE THREAD

**Issue by perigoso** [blackmagic-debug/blackmagic#1009]
The project distanced itself from "Black Magic Sphere", but the windows .inf file still has mentions

[driver/blackmagic.inf](https://github.com/blackmagic-debug/blackmagic/blob/master/driver/blackmagic.inf)

**Comment by perigoso** [comment]
the readme hosted example also shows but thats minor

**Comment by esden** [comment]
@perigoso thank you for reporting this. I hope I addressed all the remaining spots. Let me know if I missed anything. :)

**Comment by perigoso** [comment]
I just spotted a couple, apparently there were more laying around (:

The only thing that i know of, although it's not part of the actual firmware so it's really just symbolic, is the one I mentioned, in the readme

![image](https://user-images.githubusercontent.com/39195157/171950049-c604c22e-0e23-4ac6-8426-ead65dbc5d35.png)

which is an example run, but the probe is using an old version firmware that still has the black sphere string

**Comment by esden** [comment]
Good point. I ignored it "on purpose" because I was too lazy to regenerate the output. But I probably should deal with it. I am reopening this issue so that I don't forget to make that fix.
