### ISSUE TITLE
Flashing RP2040 fails if NRST pin is connected

### ISSUE THREAD

**Issue by PetteriAimonen** [blackmagic-debug/blackmagic#1013]
When I connect NRST pin to RP2040, flashing fails with error `Error erasing flash with vFlashErase packet`:

```
(gdb) mon s
Target voltage: 2.93V
Available Targets:
No. Att Driver
 1      Raspberry RP2040 M0+
 2      Raspberry RP2040 M0+
 3      Raspberry RP2040 Rescue(Attach to reset!) 
(gdb) att 1
...
(gdb) load
Sending packet: $vFlashErase:10000000,0001d000#f0...Ack
Packet received: EFF
Error erasing flash with vFlashErase packet
```

But without NRST connected, everything works fine.

The problem seems to happen at [line 553](https://github.com/blackmagic-debug/blackmagic/blob/master/src/gdb_main.c#L550-L555) in `gdb_main.c`:

```
		if (!flash_mode) {
			/* Reset target if first flash command! */
			/* This saves us if we're interrupted in IRQ context */
			target_reset(cur_target);
			flash_mode = 1;
		}
```

If I comment out the `target_reset()` call, flashing works ok. But even then `run` seems flaky.
It seems the reset by NRST pin causes black magic probe to lose connection to the RP2040, requiring new scan and attach.

I'm not sure what is the correct way to fix this, apart from just disabling NRST pin usage when connected to RP2040.

**Comment by PetteriAimonen** [comment]
Newest git (c4869a54733ae920) on ST-LINK/V2 hardware (installed natively to the STM32F103 flash, with BMP bootloader).

**Comment by PetteriAimonen** [comment]
@jamesturton @UweBonnes Have either of you tried NRST with RP2040 and BMP by any chance? It seems that it is quite common to only connect SWDIO/SWCLK in RP2040 tutorials.

**Comment by dragonmux** [comment]
Thank you for the extra information - as for the issue you're hitting.. we'll be able to do some diagnosis work the start of next week when our RP2040 boards arrive specifically to check for this kind of problem.

**Comment by PetteriAimonen** [comment]
Great :)

It's not a big issue and BMP seems to be working well for RP2040 development - it was surprisingly difficult to find a debug probe that supports it.

**Comment by UweBonnes** [comment]
Can you please add  "t->target_options |= CORTEXM_TOPT_INHIBIT_SRST;" at the end of  rp_probe(), compile,  test and report back?

**Comment by dragonmux** [comment]
Uwe, we recreated this issue, it's not quite that simple and this interacts with some other things. Please let us handle it.

**Comment by UweBonnes** [comment]
Can you please explain whaa the issue(s) is/are?
