### ISSUE TITLE
Build enhancement: Compile platforms in directory for each platform.

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#1019]
At the moment, compilation for all platforms happens in src. Compiling for a different platform as the last compile needs a "make clean" or unexpected things may happen. This needs a full recompile when testing a feature on different platforms.

**Comment by perigoso** [comment]
I think build files should go into a build directory, sub-directories for each platform to fix this, dumping the build into the source is non ideal

**Comment by esden** [comment]
As we will be reworking the build system of BMD in V2 cycle we will change how the build process works entirely making this issue redundant. I am closing this.
