### ISSUE TITLE
Direct SWD bit bang programming

### ISSUE THREAD

**Issue by estutzenberger** [blackmagic-debug/blackmagic#1063]
Does blackmagic have the capability flash files using SWD pins that are wired directly to an embedded linux processor? As in, there is no USB device. The gpio from the microprocessors SWD pins are connected directly to the main application processor.

**Comment by dragonmux** [comment]
We have been working on support for what's known as "auto-programming" where an image stored in Flash BMP-side is able to be automatically programmed to a target (over either SWD or JTAG).
The feature you're after is in the pipe to land in v2 or there about as part of an initiative to allow BMP to be used in a standalone capacity for manufacturing and other instances where some fixed binary image needs to be written to a target repeatedly.

**Comment by estutzenberger** [comment]
Great! Thanks for the response. Is there an active development branch that I could look at and perhaps modify for our needs for now?

**Comment by dragonmux** [comment]
Dev of the feature is still ongoing and on a private branch - it will be up to @esden to decide if we can push that branch public for you.

**Comment by giobauermeister** [comment]
@estutzenberger I'm currently using BMP as an SWD programmer for nRF52 processors. You can flash from a computer or even from a Raspberry Pi running Linux. You have to have GDB installed. You can leverage from batch commands like so:

```
arm-none-eabi-gdb -nx --batch -ex 'target extended-remote /dev/ttyBmpGdb' -ex 'monitor swdp_scan' -ex 'att 1' -ex 'load' your_firmware.elf
```

**Comment by dragonmux** [comment]
👋🏼 it turns out we'd entirely misinterpreted what you were after originally and that this was a request for gpiod support. Thankfully, another contributor's stepped up and written support - see PR #1773, so we'll attach this issue to that PR to be closed when it merges. We hope this is a satisfactory resolution to you.
