### ISSUE TITLE
BMDA "-d" option deprecated?

### ISSUE THREAD

**Issue by sidprice** [blackmagic-debug/blackmagic#1096]
Curious as to why this has been marked as deprecated. Seems like a useful option when you have multiple BMDPs connected. 
Sid

**Comment by UweBonnes** [comment]
The commit message that added the deprecation was "cl_utils: Clarify -d option is BMP/firmware only and deprecate -d" Looking again, that is no real reason for a deprcation, but together with the added ease of using the position or serial number argument there are few reasons to use.
