### ISSUE TITLE
Pass argument/paremeter to target script

### ISSUE THREAD

**Issue by giobauermeister** [blackmagic-debug/blackmagic#1097]
I'm looking for a way to pass a command line parameter to the target script nrf51.c so I can use this parameter together with a new command that I will implement.

eg: `monitor my_new_command 0x50`

and then use `0x50` inside `my_new_command` function implemented in nrf51.c

Is there something similar already implemented in code that I can take as an example?

I hope I expressed my idea correctly.

**Comment by dragonmux** [comment]
Here is an example of how to [use the argc and argv command parameters](https://github.com/blackmagic-debug/blackmagic/blob/main/src/command.c#L234) from command.c - this is also where the bulk of monitor commands are implemented.

For how to register your new monitor command correctly for a per-target command, see [the definition and implementation at the top of kinetis.c](https://github.com/blackmagic-debug/blackmagic/blob/feature/kinetis-cleanup/src/target/kinetis.c#L79), and [registration in kinetis.c](https://github.com/blackmagic-debug/blackmagic/blob/feature/kinetis-cleanup/src/target/kinetis.c#L372)

**Comment by dragonmux** [comment]
Going to close this issue now. If you have any further questions, please come ask in the `#blackmagic` channel [on the 1bitsquared Discord](https://discord.gg/P7FYThy). We'd be happy to help.
