### ISSUE TITLE
code style: asm inconsistency

### ISSUE THREAD

**Issue by perigoso** [blackmagic-debug/blackmagic#1120]
Right now in the code base there are multiple instances of inline assembly, but with inconsistent keywords

some are using `asm` while others `__asm__`

afaik `__asm__` is more widely supported (as asm is an extension and is not allowed by flags like std=c99 or ansi) and should be safer for naming conflicts, so that should be adopted

**Comment by dragonmux** [comment]
This issue is addressed by #1092 due to the switch to C11. Given what that's doing and how long it's taking to address testing it, we will split that PR so the utility commits around the main change are separate and merged first.

**Comment by perigoso** [comment]
Ah, i recalled seeing a commit with this chage, but couldn't find where
