### ISSUE TITLE
ADIv5: APs badly enumerated

### ISSUE THREAD

**Issue by ylm** [blackmagic-debug/blackmagic#1134]
BMP bails out if the first AP is not supported. All 8 possible APs should be checked instead.
[This line](https://github.com/blackmagic-debug/blackmagic/blob/6f81cb6a68a79efb3d29b1e0ea463557d51fd23b/src/target/adiv5.c#L793) should check if void_aps equals 8 instead.

**Comment by dragonmux** [comment]
Thank you for reporting this issue. This is indeed a regression and we have now opened a PR that fixes this buggy behaviour
