### ISSUE TITLE
BMPA build broken on OSX: aliases are not supported on darwin

### ISSUE THREAD

**Issue by djix123** [blackmagic-debug/blackmagic#1204]
Building the latest HEAD revision is broken on OSX. Build fails with the following messages:

```
target/target_probe.c:50:58: error: aliases are not supported on darwin
bool cortexa_probe(ADIv5_AP_t *apb, uint32_t debug_base) CORTEXA_PROBE_WEAK_NOP;
                                                         ^
target/target_probe.c:22:53: note: expanded from macro 'CORTEXA_PROBE_WEAK_NOP'
#define CORTEXA_PROBE_WEAK_NOP __attribute__((weak, alias("cortexa_probe_nop")))
```

**Comment by dragonmux** [comment]
Thank you for bringing this to our attention. Amy has kindly written a fix for this in the attached PR - if you'd be kind enough to test that fixes things for you that'd be grand.

This issue is set to close with that PR merging, please re-open this if it is not fixed after that point.

**Comment by djix123** [comment]
Build on OSX confirmed as working
