### ISSUE TITLE
Programming STM32L0 fails

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#1232]
> ~/devel/blackmagic/src/blackmagic gpio.bin
Black Magic Debug App v1.8.0-638-g993c74be
 for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, JLink and libftdi/MPSSE
Using 0483:374b 066FFF353830523457143715 STMicroelectronics
 STM32 STLink
Divisor for 4.0000 MHz is 0
Erasure failed!

Going back to v1.8.0-584-gaec74604 shows that erase/flashing worked before. #1231 fixes this issue.

**Comment by dragonmux** [comment]
Closing this as fixed now 1231 is merged.
