### ISSUE TITLE
STM32F1xx: Potential flash erase/write regression

### ISSUE THREAD

**Issue by mean00** [blackmagic-debug/blackmagic#1257]
Hi,
I looked into why git/main was not working on my bluepill (v1.8.2 works without problem)
When a flash operation is performed (write/erase) the logic has changed to check success
- Before : Wait till the busy bit goes to zero THEN check for errors
- Now : Wait till the busy bit goes to zero WHILE checking for errors

With the current behaviour, the very first erase fails (it tries to continue erasing anyway btw ?)
Restoring the old behaviour in stm32f1_flash_busy_wait() makes it work again (just have to move the  while 4 lines up)

The gigadevice spec (did not find the relevant part in STM doc) says to wait for BUSY to go to zero before checking for errors.

Should i try to create another broken merge request or is this just noise due to my setup and should be ignored ?
Thank you

**Comment by dragonmux** [comment]
Does #1249 fix things for you? If it does, we'll mark this issue as fixed by that and work on getting that PR merged ASAP

**Comment by mean00** [comment]
I'll test it tomorrow but i dont think that will work, my debug code was checking the EOP already and it was not set.
For information, that does work for me (tm):
--- a/src/target/stm32f1.c
+++ b/src/target/stm32f1.c
@@ -363,11 +363,11 @@ static bool stm32f1_flash_busy_wait(target *t, uint32_t bank_offset)
        uint32_t sr;
        do {
                sr = target_mem_read32(t, FLASH_SR + bank_offset);
-               if ((sr & SR_ERROR_MASK) || !(sr & SR_EOP) || target_check_error(t)) {
-                       DEBUG_WARN("stm32f1 flash error 0x%" PRIx32 "\n", sr);
-                       return false;
-               }
        } while (sr & FLASH_SR_BSY);
+       if ((sr & SR_ERROR_MASK) || !(sr & SR_EOP) || target_check_error(t)) {
+               DEBUG_WARN("stm32f1 flash error 0x%" PRIx32 "\n", sr);
+               return false;
+       }
 
        return true;
 }

**Comment by mean00** [comment]
I'm not saying this is a correct fix, just that the root cause seems to be checking for error_mask while busy bit  is still on

**Comment by dragonmux** [comment]
Ok, we'll figure out some combination of the fixes present then.

With SWD scan, does #1220 work for you? Seeing how that's another known bug we've tried to address but which needs people to let us know if the rewritten code works or regresses. Do note that this must be tested as a firmware update, it is not sufficient to use BMDA to check.

**Comment by mean00** [comment]
After a quick test,   using a bluepill based BMP to debug a STM32F103 board : 

- PR #1220 + my simple patch : SWDP scan works, erase / write flash works
- PR #1220 +PR #1249 : SWDP scan works, erase / write flash works
- 
So both solutions are making the BMP work again for me on this simple test
Thank you

**Comment by mean00** [comment]
(tested with reflashing the BMP, NOT through hosted mode)

**Comment by mean00** [comment]
on a side note,  gdb11 seems to work much better, can debug rust now. llgdb still no go.

**Comment by dragonmux** [comment]
We'll work on landing fk0815's patch and then addressing the GigaDevice datasheet item so the code works correctly with the clones then. Many thanks for this great feedback and testing :)

**Comment by mean00** [comment]
Great !
Just to be clear the problem also happens with the genuine STM32F103 part (that's what i was using)
it's just that i did not find the relevant documentation in the STM32 datasheet, but it was pretty clear in the gigadevice user manual, so it confirmed that the expected behaviour was to wait for the busy bit to clear THEN check for errors.

**Comment by dragonmux** [comment]
With the fix from fk0815 merged, and having written a patch based on the information provided here, could you  please give the patch (linked above) a whirl and tell us if it now works correctly for you?

Many thanks

**Comment by mean00** [comment]
Hi, 
I did a quick check with git/main on a stm32f103 (using swlink bmp) => all seems to work fine
Thank you

**Comment by mean00** [comment]
a bit more quick tests : 
- GD32F3  : Ok
- CH32F1  : Ko, not detected as a CH32 chip, flashing fails

**Comment by dragonmux** [comment]
With which combination(s) of PRs is that the case?

**Comment by mean00** [comment]
just git/main

**Comment by dragonmux** [comment]
It would be helpful please to test #1263 as this was targeted at your original issue, and then likewise please open a new issue with details for the CH32F1 issues - debug information such as that provided in #1252 would be ideal to include in such an issue so we can track, debug and understand what's going on so it can be fixed.

We are glad to know that merging fk0815's fix has fixed a variety of targets for you though.

**Comment by mean00** [comment]
git/main + https://github.com/blackmagic-debug/blackmagic/pull/1263/files

STM31F1  : Ok
GD32F303 : Ok
CH32F103 : Ko

(very quick test)
