### ISSUE TITLE
Build error in usb_serial.c

### ISSUE THREAD

**Issue by TaurusEight** [blackmagic-debug/blackmagic#1462]
CC      platforms/common/usb_serial.c
platforms/common/usb_serial.c: In function 'gdb_serial_control_request':
platforms/common/usb_serial.c:112:14: error: 'USB_CDC_REQ_GET_LINE_CODING' undeclared (first use in this function); did you mean 'USB_CDC_REQ_SET_LINE_CODING'?
  112 |         case USB_CDC_REQ_GET_LINE_CODING: {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              USB_CDC_REQ_SET_LINE_CODING
platforms/common/usb_serial.c:112:14: note: each undeclared identifier is reported only once for each function it appears in
platforms/common/usb_serial.c: In function 'debug_serial_control_request':
platforms/common/usb_serial.c:156:14: error: 'USB_CDC_REQ_GET_LINE_CODING' undeclared (first use in this function); did you mean 'USB_CDC_REQ_SET_LINE_CODING'?
  156 |         case USB_CDC_REQ_GET_LINE_CODING:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              USB_CDC_REQ_SET_LINE_CODING
make[1]: *** [Makefile:128: usb_serial.o] Error 1
make: *** [Makefile:17: all] Error 2

**Comment by dragonmux** [comment]
You need to run `git submodule update`. We recently updated libopencm3, and this output shows you used an existing clone and did not update the submodule.

**Comment by TaurusEight** [comment]
Thanks.
