### ISSUE TITLE
Using parts in Keil uVision without CubeMx

### ISSUE THREAD

**Issue by Michaelos10** [blackmagic-debug/blackmagic#1639]
id like to work with STM32F070RB on keil specifically without CubeMX,  but i oten get this Error: Error #545: Required gpdsc file 'C:/Users/MICHAEL/Desktop/PREMAUDA/Keil_Codes/RTE/Device/STM32F070RBTx/FrameworkCubeMX.gpdsc' is missing. How can i resolve it

**Comment by dragonmux** [comment]
(note: we have edited your issue to have a proper title and use the description for your actual issue)

Unfortunately we can't help you with your problem there as it had absolutely nothing to do with Black Magic Debug.

You are going to need to contact Keil about the issue with their IDE and documentation on how to achieve what you are after. They wrote the software in question, they know how to make it do what you're after if it can be done.
