### ISSUE TITLE
Probably typo in two meson.build files - gcc warning option

### ISSUE THREAD

**Issue by lasutek** [blackmagic-debug/blackmagic#1760]
Checked against main 2024-02-03
git rev-parse --short HEAD
813cbaf8

Probably typo in two files
./meson.build
./deps/libopencm3/meson.build
 
Line/statement
-Wunsuffixed-float-constant
should probably be
-Wunsuffixed-float-constants

If above changes are applied, 25 new warning messages show up during compilation (meson compile -C build).
../deps/libopencm3/lib/stm32/f1/rcc.c:86:17: warning: unsuffixed floating constant [-Wunsuffixed-float-constants]

**Comment by dragonmux** [comment]
👋🏼 Thanks for checking through the new build system! You are correct, those are typos - if you'd like to open a PR To both the project's fork of libopencm3 and to this repo to fix those, we'd be delighted to accept the corrections for merge.

If you feel you can fix the warnings themselves too, that'd be grand! Don't worry if you cannot though.
