### ISSUE TITLE
Meson libusb dep bad revision

### ISSUE THREAD

**Issue by perigoso** [blackmagic-debug/blackmagic#1774]
The libusb wrap references the revision `blackmagic/meson`, but this does not seem to reference any refs in the upstream, the closest being the `meson` branch, the upstream also appears to have been moved in the meantime, originally `https://github.com/dragonCodecs/libusb` which is now redirected to `https://github.com/dragonCodecs/libusb`

```
[wrap-git]
url = https://github.com/dragonCodecs/libusb
revision = blackmagic/meson
clone-recursive = false

[provide]
libusb-1.0 = libusb_dep
```

**Comment by dragonmux** [comment]
Correct, this is addressed on fix/update-deps which is pending us also doing the honours to HIDAPI. We're working on making this happen but it will take us a little while. Apologies that `main` is subsequently broken for build right now.
