### ISSUE TITLE
Flipper

### ISSUE THREAD

**Issue by Smirkio775** [blackmagic-debug/blackmagic#1801]

**Comment by dragonmux** [comment]
Why have you opened this "issue"? One word does not describe anything - please detail what you think is wrong, or what you'd like to see changed, with a title that captures a summary.

If you are referring to the Flipper Zero fork of this project, we have nothing to do with that and so please open issues with that on their fork. It's on them to update it against this repo and fix platform issues. Unless they restructure their platform to fit how this project does platforms, we will not be taking that platform in tree either as that's too high a maintenance burden.

If you do not reply back within a week, we will close this issue.
