### ISSUE TITLE
 Adding support for gd32f405

### ISSUE THREAD

**Issue by klenSA** [blackmagic-debug/blackmagic#1816]
trank code not support of  gd32f405 ( chip id 0xfa4)
simply support from diff

[GD32F405_support.diff.txt](https://github.com/blackmagic-debug/blackmagic/files/15225357/GD32F405_support.diff.txt)

**Comment by ALTracer** [comment]
Greetings. Good to hear you've found Blackmagic Debug useful with GD32F405 targets. As their Chip IDs are not listed in public documentation (I couldn't find them in datasheets or technical reference manuals ... or even application notes), do you happen to have a GD32F407 also reachable? They should be similar enough (+Ethernet MAC), and your reports of working flash reprogramming operations using the stm32f4.c BMD driver would cover both chip flavours (this goes to [Supported Targets](https://black-magic.org/supported-targets.html) table).
Your patch looks trivial enough to me, but this project is more reactive to properly filed PRs -- see [CONTRIBUTING.md](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) for a walkthrough. I noticed that you've posted GH Issues in this project previously, but no GH Pull Requests. Are there reasons blocking you from contributing this way? If so, please state so (no need to explain) and some other contributor (or even [busy] maintainers) might pick up your change [much] later.
