### ISSUE TITLE
samd: regression in `monitor swdp_scan`

### ISSUE THREAD

**Issue by maksimdrachov** [blackmagic-debug/blackmagic#1844]
I'm using a `samc21g`, support for which has been introduced in [this pull request](https://github.com/blackmagic-debug/blackmagic/pull/1659).

It works when I flash that particular commit, however it fails to recognize the MCU when I'm using v1.10.2.

Not recognizing:

![image](https://github.com/blackmagic-debug/blackmagic/assets/39975120/a43b36c9-8f84-45cf-8ab5-f40344493b51)

Recognizing:

<img width="745" alt="Screenshot 2024-06-17 at 16 35 48" src="https://github.com/blackmagic-debug/blackmagic/assets/39975120/589842f4-490c-41f0-9df4-cfd0a53c5766">

**Comment by dragonmux** [comment]
Please give latest `main` a try. It's entirely likely that the bug's already been fixed pending the v2.0 release.

**Comment by maksimdrachov** [comment]
Hi,

I've re-tried with the latest commit [aa67538](https://github.com/blackmagic-debug/blackmagic/commit/aa6753833764b41697900536395bb343f611377d) and it looks like you're right.

Thanks.

<img width="752" alt="image" src="https://github.com/blackmagic-debug/blackmagic/assets/39975120/d507af37-b5dc-4f9d-9d02-bb865a99f04d">
