### ISSUE TITLE
BMDA + orbtrace unknown ack 0x0c

### ISSUE THREAD

**Issue by robots** [blackmagic-debug/blackmagic#1890]
Trying to connect to Xplained SAM E54 using orbtrace interface.

During probing phase BMDA will probe multiple MCUs. One of them is 'samx7x'. This is done by reading certain address and confirming certain value. With SAM E54 this address does not belong to any peripheral, and the access will fail! (which is correct)

Problem is the way BMDA evaluates failed access. With XDS110 (in cmsis-dap mode) it looks like this:
```
Calling samx7x_probe
 dap_mem_read @ 400e0940 len 4, align 2
 -> dap_transfer (4 requests)
  command: 05 00 04 08 00 00 00 00 01 52 00 00 e3 05 40 09 0e 40 0f
 response: 05 04 04 40 00 00 f0 00 b0 00 00 00 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 -> transfer failed with 4 after processing 4 requests
```

With orbtrace it looks like this:
```
Calling samx7x_probe
dap_mem_read @ 400e0940 len 4, align 2
-> dap_transfer (4 requests)
 command: 05 00 04 08 00 00 00 00 01 52 00 00 e3 05 40 09 0e 40 0f
response: 05 04 0c
Access has invalid ack c
```

BMDA incorrectly interprets status byte 0c as ack C. BMDA should mask the value, and only interpret first 3 bits. Resulting in ACK fault (0b100) with Protocol error 1

After applying following patch i am able to scan the swd bus, and attach to the target.
```
diff --git a/src/platforms/hosted/dap_command.c b/src/platforms/hosted/dap_command.c
index bd72e6fe..7acb058d 100644
--- a/src/platforms/hosted/dap_command.c
+++ b/src/platforms/hosted/dap_command.c
@@ -63,7 +63,7 @@ static size_t dap_encode_transfer(

 static void dap_dispatch_status(adiv5_debug_port_s *const dp, const dap_transfer_status_e status)
 {
-       switch (status) {
+       switch (status & 0x7) {
```
I am not sure this is the correct solution for both CMSIS-DAP v1 and v2.

**Comment by dragonmux** [comment]
[Based on the documentation from ARM](https://arm-software.github.io/CMSIS-DAP/latest/group__DAP__Transfer.html) this is the correct solution (if you wish to submit a PR for this, please define a mask value for this such as `DAP_TRANSFER_STATUS_MASK` at the top of dap_command.c and set it to the constant `7U` (or as a hex literal, `0x07U`) so the magic number is named, and unsigned.

We should probably also define and handle a value, say, `DAP_TRANSFER_PROTOCOL_ERROR` as `8U`/`0x08U` to use to initiate protocol recovery as required or at least to report the protocol error state - to see if it's ever actually relevant or not.
