### ISSUE TITLE
RISC-V vs. RTT check

### ISSUE THREAD

**Issue by ALTracer** [blackmagic-debug/blackmagic#1901]
I have a few problems with this function, `target_mem_access_needs_halt()`.
https://github.com/blackmagic-debug/blackmagic/blob/ac2605cfbb6c5800a2e306ec2600bdb79f89c35c/src/target/target.c#L337-L344

It used to check via expensive strstr(), that is 1476 bytes in 4 functions on Ubuntu APT gcc/newlib, that `target->core` string contains a constant substring "RVDBG". Not a codesize problem for Arm Gnu tools newlib-nano, but impacts platforms with full newlib. 

The check is no longer valid, both `jtag_devs.c` (`descr` contained "Xambala: RVDBG013.") and `riscv_debug.c` were updated.
https://github.com/blackmagic-debug/blackmagic/commit/f7cdd28304e26a827a9c926a84bddeb40eecef69#diff-bfce42a9da0b24ee4761acf88992262feabcb50857d07f529ae7363e001e9d20L354
Now it may contain one of: "rv32" (`riscv32_probe`), "rv64" (`riscv64_probe`), "(unsup) rv128".

Rewriting to set and test target option bits may turn out a better idea. I see what needs to be done, `target->target_options |= RISCV_TOPT_NOBG` or similar, but if I touched the three probe functions and this check then I wouldn't be able to verify it myself. (Well, I have a couple ESP32-C6 and C3 boards, but they're much more complicated than a, say, GD32VF103). IIUC this is broken now and RTT is just allowed on RISC-V unconditionally. The existing TOPT bitflags are scattered across cortexm.h/cortexm.c, stm32f1.c, target_internal.h, so IMO a minor cleanup/reorganization is also needed.

**Comment by dragonmux** [comment]
This should now all be solved with #1962, so closing as merged.
