### ISSUE TITLE
Support flashing external QSPI memory

### ISSUE THREAD

**Issue by keir** [blackmagic-debug/blackmagic#194]
It'd be nice if the BM could program external flash and also set breakpoints on programs located on external flash. I realize this may be some work, and is extremely target specific. Has anyone looked at this?

**Comment by dragonmux** [comment]
So, while we're not sure which specific target(s) you had in mind, this is now a reality for RP2040 and soon also LPC43x0 targets. In the next major release of BMP there will be support for SPI Flash itself too and a more generic SPI Flash communications layer that can be used to get targets that use external Flash working where it isn't right now.

Does this answer the question?
