### ISSUE TITLE
Debugging Nuttx fails

### ISSUE THREAD

**Issue by staroselskii** [blackmagic-debug/blackmagic#38]
Don't know if this is the BMP's issue or Nuttx but if I use J-Link with the same bin, no errors come up.  

I'm trying to debug my project with BMP but debugging session fails at the start-up with this error (these messages appear on UART):

Assertion failed at file:sched_removereadytorun.c line: 105
sp:         20004a48
stack base: 20003194
stack size: 00000400
ERROR: Stack pointer is not within the allocated stack

These are commands I send:

target extended-remote /dev/ttyACM1
mon swdp_scan
attach 1
monitor vector_catch disable hard
set mem inaccessible-by-default off
set print pretty

The Nuttx config I'm using barely differs from the stm32f4discovery's one. The only difference is another pin configuration.

The bin is successfully loaded. The only problem is debugging.

**Comment by potato1992** [comment]
I have faced similar error with `ERROR: Stack pointer is not within the allocated stack`, it turns out my program use more stack memory than allocated (2K default).

**Comment by dragonmux** [comment]
Are you saying you've hit this problem on current release firmware (v1.9.2 or v1.10.0-rc0), or that your issues is historical? Is there a need for this ticket to get re-opened?

**Comment by potato1992** [comment]
> Are you saying you've hit this problem on current release firmware (v1.9.2 or v1.10.0-rc0), or that your issues is historical? Is there a need for this ticket to get re-opened?

No I was just trying to share an experience of mine, which turns out to be my configuration issue.
