### ISSUE TITLE
SW-DP scan failed! -- solved, wiring issue

### ISSUE THREAD

**Issue by drmpf** [blackmagic-debug/blackmagic#421]
Black Magic Probe (Firmware v1.6.1-1-g74af1f5) (Hardware Version 3)

I have been using BMP for some weeks now to program a NanoV2 board
as described here https://www.forward.com.au/pfod/BLE/LowPower/index.html

Today it stopped programming with error

Target voltage: 3.3V
SW-DP scan failed!

suspecting a wiring fault I hard wired the CLK and SWIO
but same error.
I have since successfully re-programmed the NanoV2 by selecting CMSIS-DAP as the programmer and then using the Redbear DAPLink V1.5 programming board.
So the chip is not the problem.

Any suggestions on how to fix this or debug it?

**Comment by UweBonnes** [comment]
Double/tripple check wiring! Missing or to few ground wires? BMP buffers not powered?  Did you try the BMP against some other hardware?

**Comment by drmpf** [comment]
As you can see from the project webpage,  https://www.forward.com.au/pfod/BLE/LowPower/index.html , the wiring is fixed and unchanging for the last month.

I have just tested the continuity of the ribbon cable from the BMP JTAG header's board pins to the breakout board pins.  No breaks there.

Not sure what 'buffers not powered' means but BMP report the Nano's VCC correctly.

I tested the Computer software, usb, etc by replacing the BMP with a clone, Electronut.it Bumpy and it worked without problems, plugging into the sockets the BMP breakout header would plug into (see the detailed layout on the web page). 

This implies the wiring and hardware downstream of the BMP ribbon cable/header is OK and works and that the driving software is running correctly.

That only leaves the BMP at fault
