### ISSUE TITLE
EFM32 driver doesn't support recovering locked parts 

### ISSUE THREAD

**Issue by richardeoin** [blackmagic-debug/blackmagic#436]
Parts are locked by clearing the Debug Lock Word (DLW)

**Comment by perigoso** [comment]
should be closed as per
5943552a6b1f54ab9add80a87f64945db00b7769
and
#567

**Comment by perigoso** [comment]
thats because I deleted it, this one is actually not implemetned (doesnt look like it to me at least), sorry for the confusion

**Comment by dragonmux** [comment]
Oh, huh - indeed, the linked PR doesn't look to fix this. Re-opening till we can otherwise prove it's implemented

**Comment by perigoso** [comment]
according to Silabs, the correct method to clear the debug lock word is to issue a mass erase through the AAP, which is in fact implemented by `efm32_aap_cmd_device_erase`, so this too should be closed.

**Comment by dragonmux** [comment]
Thank you for checking this. Closing.
