### ISSUE TITLE
Multi-core support

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#512]
STM  An5286 lists the requirements for a multi-core aware debugger:
To ensure dual debug, a debugger must offer:
· 1   access port selection capability
· 2    simultaneous multiple core connection capability using the same debug probe
· 3   visibility of all cores
· 4   support of cross trigger Arm® component
·  5  possibility to switch between access ports during the same debug session to visualize  memory and peripherals statutes in the other domains.

At the moment, BMP supports only 1 and 3. Contributions wanted.

**Comment by esden** [comment]
As we only support one GDB instance, and GDB does not support attaching to multiple processes at once, we will not be able to support point 2, and thus also point 4 is not really useful. Supporting multiple GDB instances is out of scope of the project. We do currently support 1, 3 and 5 and I consider the rest as `wont-fix`. 

With that, closing this issue.
