### ISSUE TITLE
#define SAMD_DID_SERIES_MASK		0x1F

### ISSUE THREAD

**Issue by hsn93** [blackmagic-debug/blackmagic#571]
im reading [samd21 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf) 

on this [**section 13.13.9**](http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf#_OPENTOPIC_TOC_PROCESSING_d115e38553)

i think
#define SAMD_DID_SERIES_MASK		0x1F
https://github.com/blacksphere/blackmagic/blob/master/src/target/samd.c

should be 0x3F

**Comment by UweBonnes** [comment]
Do you see any impact when changing the mask? Are there any parts that define 0x1f as mask?

**Comment by hsn93** [comment]
i didnt check the impact.
i dont know about other parts but:
i know SAMD21, SAMD20 ,SAMD10, and SAMD11 are all series mask 0x3F

however, checking on datasheet SAMD11 seems like only two values are being used only

|  SERIES[5:0]  	|   Description                                            |   	     
|:-:	                |:-	                                                         |
|   0x0              |  Cortex-M0+ processor, basic feature set |   	
|  0x1               |  Cortex-M0+ processor, USB                    |   	
|  0x2-0x3F      |   Reserved                                                 |   	

 but this data isnt available on samd21 datasheet

**Comment by esden** [comment]
Is there a good reason to proactively expand the mask from 0x1F to 0x3F? Should we leave it as it is until it turns out to be an issue with some future part or change it now? I am pretty much ok with both solutions considering that most of the bits seem to be reserved and not used on the currently existing parts.

**Comment by dragonmux** [comment]
Looking this over, for correctness with the datasheet, we should use the 0x3F mask to future proof the code better. We'll get a PR in that closes this issue for v1.9
