### ISSUE TITLE
Leave devices in better state after probe and after debug session

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#612]
E.g. at the moment for STM32 we set DBGMCU_CR to allow debug in sleep and perhaps deeper sleep states. This causes increase device current consumption. This state persist after probe and after the debug session. For all ADIV5 devices we also have keep debug powered up.

Find a way to transparently undo this modifications in a transparent way.

**Comment by dragonmux** [comment]
This has now been sorted in v2.0 PRs #1882 and #2013, so closing as fixed.
