### ISSUE TITLE
Recover from hard faults

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#656]
When reading from illegal memory, e.g. F4 Option bytes with Level 1 readout protection active, BMP native gets out of sync. Harden BMP to revover from that situation.

**Comment by dragonmux** [comment]
If we understand what this was, this has been fixed as of #1360 and #1371 - please confirm.

**Comment by dragonmux** [comment]
Given this looks to be fixed in the v1.9 firmware and entirely fixed in BMDA as of v1.10/main, closing as fixed.
