### ISSUE TITLE
Support for LPC55?

### ISSUE THREAD

**Issue by jans23** [blackmagic-debug/blackmagic#736]
I see blackmagic doesn't support LPC55. Is support for LPC55 planned or do any unofficial patches exist for such?

**Comment by UweBonnes** [comment]
BMP is a community effort. Somebody must have some LPC55 board and write and test support for it.

**Comment by UweBonnes** [comment]
There is support for LPC54 now in master. Perhaps LPC55  only requires small changes?

**Comment by esden** [comment]
@jans23 Do you want to comment on this? All we might need is to add the correct ID to the BMP firmware and your device will be supported.

**Comment by jans23** [comment]
Didn't had time to test it yet.

**Comment by esden** [comment]
Ok, sounds good. :)

**Comment by UweBonnes** [comment]
Please have a look at https://github.com/UweBonnes/blackmagic/tree/lpc55. It  puts detecting the device on more solid ground. I have a MCULINK to test things, but I do not understand the device good enough to add the memory map and I do not feel like I have time to implement the flashing algo.  #849 needs also to be considered.

**Comment by dragonmux** [comment]
Support for this is now slated to land in v1.10
