### ISSUE TITLE
LPC: Page vs Sector erase, reserved boot rom pages

### ISSUE THREAD

**Issue by UweBonnes** [blackmagic-debug/blackmagic#887]
LPC Common and the LPC flash structure only allow sector erase. E.g. the LPC802 has the top pages 254 and 255 reserved fixed for the Boot Rom. Page erase is needed to use the  remaining pages of the top sector.

**Comment by dragonmux** [comment]
It looks like this was fixed in [lpc_common.c:196](https://github.com/blackmagic-debug/blackmagic/blob/main/src/target/lpc_common.c#L196) - is this issue stale?

**Comment by dragonmux** [comment]
Closing as solved as it appears to be a fixed bug.
