### ISSUE TITLE
Request SAMC21 support

### ISSUE THREAD

**Issue by ikcalB** [blackmagic-debug/blackmagic#890]
I did buy the BMP to support this awesome project, just realising that my required platform is not yet supported (SAMC21).

Has there been any work on this so far?

If not, I might try to add support.
Skimming through the sources I suppose there is more, than just replacing 's/samd/samc/'.
Is there a starting point for porting?

Best regards from Austria,
Florian

**Comment by UweBonnes** [comment]
I have not much experience with SAM, STM32 is much better known to me. For a new platform, find out if there is familiarity with already existing platforms. The entry page of the NVMCTRL section of the SAMD2 and SAMC2 family datasheets seems very similar. Work out the differences and test. Eventually spy at OpenOCD and pyOcd code for those devices.

When implementing target algorithms, I perfer using BMP hosted as no constant firmware upload is needed. 

Consider chatting in the discord channel

**Comment by franzflasch** [comment]
Any news on this? From what I see openocd does not seem to treat the SAMC and SAMD devices differently. I guess it should be only some minor adaption to target/samd.c to make it work.

**Comment by perigoso** [comment]
*(I'm not an official maintainer)* From what I looked at the time adding support for the SAMC should be trivial, but without personal interest or a device to test on I didn't Implement it myself, I don't think anyone else did and looking at the source seems to confirm this.

**Comment by dragonmux** [comment]
There is support in development - we need to encourage the user in question to contribute it upstream to this repo with a PR. SAMC has subtly a different Flash controller and different identification information so the support is actually a fork of the SAMD support right now.

Failing that, we'll hopefully get to implementing support in the v2.0 cycle

**Comment by franzflasch** [comment]
Is that code available somewhere? I have a samc21 here and i could test it.

**Comment by dragonmux** [comment]
Unfortunately not yet publicly - we'll make sure this issue ticket gets roped into whatever eventual PR when it is made public so you'll be able to know about it though.

**Comment by franzflasch** [comment]
In case someone is interested: As a quick and dirty hack I changed the SAMD_DID_CONST_VALUE in target/samd.c:
```
-#define SAMD_DID_CONST_VALUE   0x10000000U
+#define SAMD_DID_CONST_VALUE   0x11000000U
```

Not sure what the SAMD_DID_CONST_VALUE is supposed to be anyway. 

Now I am able to flash the SAMC21.
