### ISSUE TITLE
Set SWCLK and SWDIO to Hi-Z on detatch

### ISSUE THREAD

**Issue by emeb** [blackmagic-debug/blackmagic#945]
There are many cases where the SWD interface pins are re-purposed in the target application - eg those pins are remapped for other GPIO / peripheral interfaces when the embedded firmware is running. In these cases the SWD interface is only available immediately after power-up while the NRST is asserted. After programming and subsequent reset there will be contention on the SWD pins if the BMP continues to drive these signals, so it's desirable for the BMP to set these pins to Hi-Z after completing the programming cycle.

Current native BMP hardware uses external buffers between the STM32F103 MCU running BMP firmware and the target and will not be able to completely disable the SWD lines, but non-native hardware (and much older versions of BMP) will still benefit if these pins are disabled on the STM32F103.

Note that simply disabling the SWD buffers by means of TPWR is not sufficient since it's still necessary to power the target.

**Comment by UweBonnes** [comment]
STLINK V21 and V3 can switch power and due to no voltage translation buffers can tristate SWCLK and SWDIO. Both have a BMP firmware variant and so can be used for experiments and setting up the needed firmware changes

**Comment by esden** [comment]
Thanks @emeb that is a good suggestion. It is bit tricky to do, but I will see if I can find an extra gpio on the mcu to allow control. No promisses but it is a good idea.

**Comment by esden** [comment]
Hey @emeb,

So I think I managed to squeeze in the ability to control the SWCLK/TCK level shifter direction. (that also controls TDI, but I don't think we care about that) This way we should be able to set SWDIO and SWCLK to input, setting them to Hi-Z when idle. See highlighted parts of the attached schematic.

Let me know what you think.

![bmpm23b-sch-highlighted](https://user-images.githubusercontent.com/17334/160490387-646f9f7e-8487-4a22-9e06-199d024706c5.jpg)

**Comment by emeb** [comment]
Excellent news. Looking forward to trying it out!
