### ISSUE TITLE
Blackmagic FW gets stuck in blocking_handler() on flashing an NRF52

### ISSUE THREAD

**Issue by MikeDK** [blackmagic-debug/blackmagic#960]
In our project, we want to use the black magic probe as a less pricey alternative to a jlink, because we need quite a lot of probes for our automatic testing.
We wrote gdb scripts to automate some stuff, like doing a mass erase followed by writing some bytes into the UICR and then flashing a fw hex file via file/load.

When running those scripts several times, the probe eventually gets stuck within the fw file flashing just after the output of it loading the first section (Loading section .sec1, size 0x10000 lma 0x0)

This happens on three different probe platforms:

- 1bitsquared Black Magic Probe v2.1e
- ST-LINK/V2
- 'baite' stlink clone

So I guessed this is somehow bmp fw related.

I soldered some wires to the 1bitsquared probe to debug it via a jlink using the blackmagic.elf file and tried to reproduce it, which gave me following call stack when the error happens:

blocking_handler@0x0801124a (/home/mikedk/src/ng/blackmagic/libopencm3/lib/cm3/vector.c:104)
<signal handler called>@0xfffffff9 (Unbekannte Quelle:0)
_malloc_r@0x08011a0e (/_malloc_r.cdasm:39)
target_flash_write_buffered@0x0800ecf0 (/home/mikedk/src/ng/blackmagic/src/target/target.c:293)
target_flash_write@0x0800f014 (/home/mikedk/src/ng/blackmagic/src/target/target.c:263)
handle_v_packet@0x0800614a (/home/mikedk/src/ng/blackmagic/src/gdb_main.c:504)
gdb_main_loop@0x080068a8 (/home/mikedk/src/ng/blackmagic/src/gdb_main.c:314)
gdb_main@0x080068ea (/home/mikedk/src/ng/blackmagic/src/gdb_main.c:553)
main@0x08008a48 (/home/mikedk/src/ng/blackmagic/src/main.c:47)

So somehow the malloc fails and triggers a hardfault which then gets stuck within blocking_handler().

The only way to get the probe up and running again is to replug the USB connection.

For us, this is a blocking issue because the effort needed to automatically disconnect/reconnect the usb connections of a lot of probes would exceed the price of a stlink/v2 by quite a lot ;)

So please tell me if I can collect some more symptoms to help get this bug fixed.

Regards,
MikeDK

**Comment by MikeDK** [comment]
PS: The blackmagic FW Version is 1.7.1

**Comment by UweBonnes** [comment]
Hello Mike,

thanks for the report. This smells like a hidden memory leak.

Can you try git head if that is fixed by recent changes? Compiling with ASAN, leak reported where fixes before and after  v1.7.1. On linux, git head can also be compiled "make PROBE_HOST=hosted ASAN=1" to run with AddressSanitizer and debug messages get displayed on the starting console after starting the resulting binary and connecting to :2000 instead of /dev/ttyACMx.

The NRF code only has allocation when attaching. so I suspect NRF code is not the reason. Can you provide the (stripped down) scripts?

**Comment by MikeDK** [comment]
Hello Uwe,

I tried the git head about two weeks ago, but with that the monitor swdp_scan command unfortunately found no targets.

The scripts basically do the following...:
```

### some initial stuff
set confirm off
set mem inaccessible-by-default off

### connect the probe
target extended-remote /dev/ttyACM0

### resetting the target
# do an swdp scan, attach first target and do a mass erase
monitor swdp_scan
attach 1
monitor erase_mass
# now do a detach because if nrf52 app protect was active, there was only 1 target (nrf52 access port)
# which can only do a mass erase (besides throwing some gdb exceptions) and afterwards app protect is gone
detach
# a new swdp scan will now detect 2 targets, where the first one is the one of interest
# if app protect was not active, this is just a repeat of above
monitor swdp_scan
attach 1

### now we do some writing to the UICR
# first enable write in NVMC
maintenance packet M 0x4001E504,0x00000004:01000000
# then write some data
maintenance packet M 0x10001080,0x00000008:010203040506FFFF
# enable read again in NVMC
maintenance packet M 0x4001E504,0x00000004:00000000

### firmware flashing
# load hex file
file very_secret_firmware_file.hex
load

```

I can reproduce the error also when doing those commands in an interactive gdb session, so it's likely not a timing issue. I agree with the idea that this smells like a memory leak ;)

The firmware is rather big - hex file is about 1.2 MB and contains about 440 kB of code data to flash.
I would bet that this fact is part of the problem.

**Comment by MikeDK** [comment]
PS: I forgot to mention that I can not reproduce this always in the same manner ... so sometimes it happens the very first time after the probe is connected to USB, then sometimes it needs 10 loops for the error to happen...
It seems it does also happen no matter if the app protect is active or not .... sometimes it needs a target power cycle to happen, sometimes not

Unfortunately I could not recognize any pattern which leads to the error :/

So this unpredictability could probably point in the timing issue direction

**Comment by MikeDK** [comment]
PPS: I also tried different hosts (rpi3, rpi4, x86_64 amd/intel) and several gdb versions on that hosts (8, 9, 10, arm-none-eabi-gdb or gdb-multiarch) before debugging the probe itself...

**Comment by dragonmux** [comment]
From the look of this, the code for handling Flashing is allocating (seems like a red flag). We will dive into this and see if a) it's still a problem on main and therefore with the v1.8 firmware, and b) if we can avoid allocating or otherwise make sure that allocations are properly matched with `free()` calls to avoid this issue to start with.

Depending on what we find, we will either open a PR with a fix or update this issue with our findings.

**Comment by MikeDK** [comment]
PS: I tried with the 1bitsquared 2.1 platform ... I will try it also with an STLINK/V2 just to be sure ... If I find some any problem, I will reopen the issue ;)

**Comment by MikeDK** [comment]
Ok seems like the patch also works for STLINK ... BUT I can only get it to work if I manually apply the patch from the PR onto the 1.7.1 tag of the firmware.... since 1.8.0 the command swdp_scan is not working anymore for an stlink platform ...
But I guess I have to open another issue for that one ;)

**Comment by dragonmux** [comment]
Please do with as much detail as you can. As far as we knew, that was working just fine (it might not be SWDP scan itself that's broken but rather scan on the specific target.. there's work going on to figure out why it's become unreliable and improve it)

**Comment by MikeDK** [comment]
ok I will try to enable the debug messages in the fw ...

What is strange is that with the 1bitsquared platform and 1.8.0, swdp_scan works without problems ... so my guess is the problem is not in the target code (which would be nrf52 in my case) but rather somewhere in the platform code

**Comment by MikeDK** [comment]
We just had another look at the stablity after the patch, and unfortunately my colleague was able to reproduce the error after about 15 retries.

So it seems like the problem occurs less frequently, but is not completely gone :/

On a sidenote: We decided to do a little workaround, and so I implemented a new monitor command to to be able to reboot the probe after one cycle of ours ... this should reduce the probability for the error to nearly zero ... So if someone is interested in that code, I post it here...:
```
diff --git a/src/command.c b/src/command.c
index 2758d31..c67bb18 100644
--- a/src/command.c
+++ b/src/command.c
@@ -46,6 +46,7 @@ struct command_s {
 
 static bool cmd_version(target *t, int argc, char **argv);
 static bool cmd_help(target *t, int argc, char **argv);
+static bool cmd_platform_boot(target *t, int argc, char **argv);
 
 static bool cmd_jtag_scan(target *t, int argc, char **argv);
 static bool cmd_swdp_scan(target *t, int argc, char **argv);
@@ -68,6 +69,7 @@ static bool cmd_debug_bmp(target *t, int argc, const char **argv);
 const struct command_s cmd_list[] = {
        {"version", (cmd_handler)cmd_version, "Display firmware version info"},
        {"help", (cmd_handler)cmd_help, "Display help for monitor commands"},
+       {"platform_boot", (cmd_handler)cmd_platform_boot, "Request reboot of probe"},
        {"jtag_scan", (cmd_handler)cmd_jtag_scan, "Scan JTAG chain for devices" },
        {"swdp_scan", (cmd_handler)cmd_swdp_scan, "Scan SW-DP for devices" },
        {"targets", (cmd_handler)cmd_targets, "Display list of available targets" },
@@ -167,6 +169,18 @@ bool cmd_help(target *t, int argc, char **argv)
        return true;
 }
 
+bool cmd_platform_boot(target *t, int argc, char **argv)
+{
+       (void)t;
+       (void)argc;
+       (void)argv;
+
+       gdb_out("Rebooting...");
+       platform_request_boot();
+
+       return true;
+}
+
 static bool cmd_jtag_scan(target *t, int argc, char **argv)
 {
        (void)t;
```

**Comment by dragonmux** [comment]
Once we've cleared down a little more of the current tranch of work for v1.9, we did intend to go looking again at buffer lifetime bounding and generally at allocation lifetimes and see what we can shorten and how we can improve things there as we think it's a hot mess right now - hopefully if we can get that under control it'd obviate the need for such a command, but we're glad you have a workaround for now

**Comment by dragonmux** [comment]
@MikeDK could you try #1205 and see if Perigoso's work which should have bounded the lifetimes of those buffers further fixes things for you? If so, we'll link the issue to that PR

**Comment by MikeDK** [comment]
@dragonmux sorry I had no time until now to check that ... and now I am facing problems testing the change because of the swdp_scan issue in the main branch - #1104 
I tried cherrypicking the commits of the PR into v1.7.1, but there were so much conflicts, I gave up after 5 minutes ;)
My only option for now is to try the main branch on the 1bitsquared hw, but as this has more ram (i guess), i believe the error will be harder to reproduce

**Comment by dragonmux** [comment]
You should be able to use 1.8.2 or even main with all 3 of your probes (`make PROBE_HOST=swlink` for the ST-Link clone and `make PROBE_HOST=stlink ST_BOOTLOADER=1` for your ST-Link v2). We're not terribly surprised that you couldn't backport the changes to v1.7.1 with the large structural changes that both Uwe and us have made since that release.

Perigoso's suggestion is solid for what it's worth. As for not having had time, not to worry. We're in a feature freeze now but there's time yet till we do the v1.9rc1 release.

**Comment by MikeDK** [comment]
@perigoso thnx for the hint, I tried the swd-timings branch, but unfortunately the swdp_scan command is not working there too

@dragonmux i did not try the st-link clone yet to see if it also has the swdp_scan issue, but fact is: upwards v1.7.1 the swdp_scan does not work on a official stlink/v2 ... on the 1bitsquared platform the scan works

yesterday I was finally able to debug the stlink platform ... after trying unsuccessfully (for much too long) with the stlink bootloader, I flashed the bmp dfu bootloader and was then able to do debugging work with the .elf file
I could see that in the adiv5_swdp_scan() function something went wrong, and I wanted to compare the behaviour to the 1bitsquared platform, but unfortunately my solder equipment at home is too bad to get the old broken wires out of the solder holes :D
so I will have to wait until next week to get a fresh batch of debug wires onto the probe by our electronic guys ;)

Until then, if I find any useful information through my debugging adventures, I will post that in the other issue

**Comment by dragonmux** [comment]
With your issues with SWD scan on the fix/swd-timings branch, could you please leave a testing report with your findings and methodology over on #1220 as that's our first negative on that branch having fixed SWD reliability so we'd like to dive into what's going on and see if the issue we're trying to fix in that branch isn't actually, or if it's another compounding issue that needs looking at.

**Comment by UweBonnes** [comment]
Keep in mind that  NRF52 uses 1.8 Volt as SWJ IO-voltage as long as no programm has switched it to 3.3 Volt. So only a level translating adapter can work.

**Comment by MikeDK** [comment]
@dragonmux I can do that next week as on monday and wednesday I am in the office and there I have a logic analyzer and an oscilloscope ... maybe we can find out more with some measurements

@UweBonnes Ok then I wonder why swdp_scan is working with a v1.7.1 bmp fw, but not with a newer one. I can definitively reproduce that ... As soon as I flash v1.7.1 to the stlink, the swdp_scan works, and when I then use master or swd timing fix branch, it does not work any more

**Comment by dragonmux** [comment]
👋🏼  @MikeDK if possible could you re-test this with latest `main` and tell us if your issue is now resolved or if it's still busted?

**Comment by dragonmux** [comment]
As it's been a couple more months and we've not had anyone else report this issue, we will close it. If the issue is not resolved, please let us know and we'll re-open it and work with you further to solve it.
